# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministracionComisionInventario',
            fields=[
                ('numero', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('inicioadministracion', models.DateField()),
                ('finadministracion', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdministracionComisionProconstruccion',
            fields=[
                ('numero', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('inicioadministracion', models.DateField()),
                ('finadministracion', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdministracionMinistro',
            fields=[
                ('numero', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('inicioadministracion', models.DateField()),
                ('finadministracion', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Iglesia',
            fields=[
                ('clave', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=30)),
                ('municipio', models.CharField(max_length=40)),
                ('colonia', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=40)),
                ('cp', models.IntegerField()),
                ('telefono_fijo', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('clave', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=30)),
                ('municipio', models.CharField(max_length=40)),
                ('colonia', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=40)),
                ('cp', models.IntegerField()),
                ('telefono_fijo', models.CharField(max_length=14)),
                ('iglesia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iglesia.Iglesia')),
            ],
        ),
        migrations.AddField(
            model_name='administracionministro',
            name='iglesia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iglesia.Iglesia'),
        ),
    ]
