# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BienInmueble',
            fields=[
                ('clave', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('entidad_federativa', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('colonia', models.CharField(max_length=50)),
                ('calle_numero', models.CharField(max_length=50)),
                ('cp', models.IntegerField()),
                ('colindacion_norte', models.CharField(max_length=50)),
                ('colindacion_sur', models.CharField(max_length=50)),
                ('colindacion_este', models.CharField(max_length=50)),
                ('colindacion_oeste', models.CharField(max_length=50)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('documento', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('lugar_expedicion', models.CharField(max_length=50)),
                ('fecha_expedicion', models.DateField()),
                ('nombre_propietario', models.CharField(max_length=50)),
                ('situación_juridica', models.CharField(max_length=50)),
                ('superficie_terreno', models.IntegerField()),
                ('superficie_construida', models.IntegerField()),
                ('edificaciones', models.IntegerField()),
                ('niveles', models.IntegerField()),
                ('uso', models.CharField(max_length=50)),
                ('zona', models.CharField(max_length=50)),
                ('servicios', models.TextField()),
                ('foto1', models.ImageField(upload_to='fotos')),
                ('foto2', models.ImageField(upload_to='fotos')),
                ('foto3', models.ImageField(upload_to='fotos')),
                ('foto4', models.ImageField(upload_to='fotos')),
                ('lat', models.CharField(max_length=50)),
                ('lng', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('numero_factura', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('rfc_provedor', models.CharField(max_length=50)),
                ('nombre_provedor', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('total', models.IntegerField()),
                ('archivo', models.FileField(upload_to='Facturas')),
                ('tipo_pago', models.CharField(choices=[('efectivo', 'efectivo'), ('transferencia', 'transferencia')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialEspecie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('cantidad', models.CharField(max_length=50)),
                ('costo_aproximado', models.IntegerField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('folio', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('concepto', models.CharField(choices=[('mantenimiento', 'Mantenimiento'), ('remodelacion', 'Remodelacion'), ('ampliacion', 'Ampliacion'), ('provicional', 'Construccion provicional'), ('definitiva', 'Construccion definitiva')], max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('costo_aproximado', models.IntegerField()),
                ('tiempo_aproximado', models.IntegerField()),
                ('estado', models.CharField(choices=[('proceso', 'proceso'), ('suspendido', 'suspendido'), ('cancelado', 'cancelado')], max_length=50)),
                ('saldo_disponible', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RecaudacionFondos',
            fields=[
                ('clave', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('proposito', models.CharField(choices=[('compra', 'compra de terreno'), ('construccion_provicional', 'construccion provicional'), ('construccion_definitiva', 'construccion definitiva'), ('mantenimiento', 'mantenimiento'), ('remodelacion', 'remodelacion'), ('ampliacion', 'ampliacion')], max_length=50)),
                ('forma', models.CharField(choices=[('colectas', 'colectas'), ('ventas', 'ventas')], max_length=50)),
                ('saldo_disponible', models.IntegerField()),
                ('estado', models.CharField(choices=[('activa', 'activa'), ('cancelada', 'cancelada'), ('finalizada', 'finalizada')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('clave', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('mes_año', models.CharField(max_length=40)),
                ('saldo_anterior', models.IntegerField(null=True)),
                ('total_ingresos', models.IntegerField(null=True)),
                ('total_salidas', models.IntegerField(null=True)),
                ('saldo_final', models.IntegerField(null=True)),
                ('fecha_elaboracion', models.DateField(auto_now_add=True)),
                ('donaciones_especie', models.IntegerField()),
                ('estatus', models.IntegerField(choices=[('1', 'espera'), ('2', 'aprovado por el ministro'), ('3', 'rechazado por el ministro'), ('4', 'aceptado'), ('5', 'denegado')])),
            ],
        ),
        migrations.CreateModel(
            name='ReporteRecaudacion',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('saldo_anterior', models.IntegerField()),
                ('cantidad_recuadada', models.IntegerField()),
            ],
        ),
    ]
