# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iglesia', '0001_initial'),
        ('bienesinmuebles', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporterecaudacion',
            name='comision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.ComisionProConstruccion'),
        ),
        migrations.AddField(
            model_name='reporterecaudacion',
            name='recaudacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bienesinmuebles.RecaudacionFondos'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='ministro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Ministro'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bienesinmuebles.Proyecto'),
        ),
        migrations.AddField(
            model_name='recaudacionfondos',
            name='iglesia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iglesia.Iglesia'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bienesinmuebles.BienInmueble'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='recaudacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bienesinmuebles.RecaudacionFondos'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Ministro'),
        ),
        migrations.AddField(
            model_name='materialespecie',
            name='reporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bienesinmuebles.Reporte'),
        ),
        migrations.AddField(
            model_name='factura',
            name='reporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bienesinmuebles.Reporte'),
        ),
        migrations.AddField(
            model_name='bieninmueble',
            name='iglesia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iglesia.Iglesia'),
        ),
        migrations.AddField(
            model_name='bieninmueble',
            name='obra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iglesia.Obra'),
        ),
    ]
