# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mueble',
            fields=[
                ('clave', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('subarea', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=50)),
                ('tamano_metros', models.IntegerField()),
                ('tiempo_vida', models.IntegerField()),
                ('tipo', models.CharField(max_length=50)),
                ('valor_estimado', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='fotos')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudBaja',
            fields=[
                ('clave_solicitud', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('razon', models.CharField(max_length=70)),
                ('estado_solicitud', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudCompra',
            fields=[
                ('clave_solicitud', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('costo_aproximado', models.IntegerField()),
                ('fotografia1', models.ImageField(upload_to='')),
                ('fotografia2', models.ImageField(upload_to='')),
                ('estado_solicitud', models.CharField(max_length=50)),
            ],
        ),
    ]
