# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iglesia', '0001_initial'),
        ('bienesmuebles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcompra',
            name='iglesia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iglesia.Iglesia'),
        ),
    ]
