# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iglesia', '0001_initial'),
        ('bienesmuebles', '0002_solicitudcompra_iglesia'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcompra',
            name='ministro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Ministro'),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='obra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iglesia.Obra'),
        ),
        migrations.AddField(
            model_name='solicitudbaja',
            name='iglesia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iglesia.Iglesia'),
        ),
        migrations.AddField(
            model_name='solicitudbaja',
            name='ministro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Ministro'),
        ),
        migrations.AddField(
            model_name='solicitudbaja',
            name='mueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bienesmuebles.Mueble'),
        ),
        migrations.AddField(
            model_name='solicitudbaja',
            name='obra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iglesia.Obra'),
        ),
        migrations.AddField(
            model_name='mueble',
            name='iglesia',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='iglesia.Iglesia'),
        ),
        migrations.AddField(
            model_name='mueble',
            name='obra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iglesia.Obra'),
        ),
    ]
